### ISSUE TITLE
Two trains become connected

### ISSUE THREAD

**Issue by ChuckSavage** [NoxyNixie/Noxys_Multidirectional_Trains#7]
I was kind of wondering why this hadn't happened yet. Honestly, this could (may need to be) bumped up to Factorio bug. `connect_rolling_stock(direction)` really should be `connect_rolling_stock(entity)`. Or at least have that call available.

Here's the [screenshot](https://pasteboard.co/HfBJ9RIQ.png). In this case a stone train became connected to a copper plate train. The copper plate train was taken to the stone drop off, and since the train was too long, couldn't leave.

As I was typing this, the mod threw an error. Here's the [screenshot](https://pasteboard.co/HfBKFUl.png), and I'll attach the factorio_current log file if you want it.  [factorio-current.log](https://github.com/CyaNox/Noxys_Multidirectional_Trains/files/1887028/factorio-current.log)

**Comment by NoxyNixie** [comment]
Well this can only really happen if your blocks are just large enough for two trains to be close enough to connect. Spacing out the blocks would prevent this from happening.

One of the changes I made makes it completely ignore what direction it is connected to and what direction it needs to reconnect to. This change makes it possible for trains too close to connect. That change did fix "some" of the disconnection issues we've had so I'm not sure if this should be reverted or not fixed at all since you can fix it by moving some of your signals.

**Comment by ChuckSavage** [comment]
> ... not fixed at all since you can fix it by moving some of your signals.

Well, for new maps that can be planned for. You've obviously not loaded my map.

Close to 200 trains run around [this, see screenshot](https://pasteboard.co/HfGUrBO.png).

**Comment by NoxyNixie** [comment]
I'm closing this one since I'm not likely to fix the linking up ever. I did add a warning on the mod page about this.

The crash error should be fixed in 0.0.7.
